### ISSUE TITLE
Custom element doesn't exist: browser-control-card

### ISSUE THREAD

**Issue by AlexQuaken** [mathoudebine/homeassistant-browser-control-card#11]
Stop working one week ago

![image](https://github.com/mathoudebine/homeassistant-browser-control-card/assets/61948337/cb492dd3-916d-4917-b9a8-c640c2dbd6fb)

**Comment by AlexQuaken** [comment]
GET https://unpkg.com/@lit/reactive-element@2.0.0/reactive-element.js?module net::ERR_ABORTED 500 (Internal Server Error) 

https://unpkg.com/lit?module is get wrong answer, in browser console, so I try change in the code> but it now work (((

Replace this line in your code:

import { html, css, LitElement } from "https://unpkg.com/lit?module";

import { html, css, LitElement } from "https://cdn.jsdelivr.net/npm/lit@latest?module";

Downgrade to version 1.0 it is work now

**Comment by mathoudebine** [comment]
Hi @AlexQuaken this issue is now fixed on v1.3.1! Feel free to update through HACS
