### ISSUE TITLE
Control of functions directly from HA (creation of entity?)

### ISSUE THREAD

**Issue by Alessiou78** [mathoudebine/homeassistant-browser-control-card#17]
1st, TKS for your work.
Is it possible to implement a "full screen button" control, and maybe other buttons, directly from HA? (perhaps through a creation of the related entities)

**Comment by mathoudebine** [comment]
Unfortunately it is not possible from a card to create sensors or services, but you can use Browser Mod to do this: https://github.com/thomasloven/hass-browser_mod 

First install Browser Mod from HACS, and configure it by following the documentation here: https://github.com/thomasloven/hass-browser_mod?tab=readme-ov-file#quickstart

Once you have registered your web browser with Browser Mod, you can run javascript code to the browser from a Home Assistant service called `browser_mod.javascript`.

For example if you want your browser to go fullscreen, call this service with your browser as target:

![browser-mod](https://github.com/user-attachments/assets/9ad76927-edc5-452d-944f-67ac983e4804)

Then you can call this service from automation, or from a button card...

There are some other javascript codes, e.g. to refresh the page the javascript code is `document.location.reload();`

**Comment by Alessiou78** [comment]
TOP ! Thanks a lot

**Comment by jouster1974** [comment]
> Unfortunately it is not possible from a card to create sensors or services, but you can use Browser Mod to do this: https://github.com/thomasloven/hass-browser_mod
> 
> First install Browser Mod from HACS, and configure it by following the documentation here: https://github.com/thomasloven/hass-browser_mod?tab=readme-ov-file#quickstart
> 
> Once you have registered your web browser with Browser Mod, you can run javascript code to the browser from a Home Assistant service called `browser_mod.javascript`.
> 
> For example if you want your browser to go fullscreen, call this service with your browser as target:
> 
> ![browser-mod](https://private-user-images.githubusercontent.com/38615348/352589640-9ad76927-edc5-452d-944f-67ac983e4804.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3OTM4MDUsIm5iZiI6MTczMjc5MzUwNSwicGF0aCI6Ii8zODYxNTM0OC8zNTI1ODk2NDAtOWFkNzY5MjctZWRjNS00NTJkLTk0NGYtNjdhYzk4M2U0ODA0LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI4VDExMzE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NjAzOGRkMWQ2MjM2MmI4MjQ0NTE0ZDY5NzhkZTIzMWI0MGI5MWJmNjhlZTM2NDZjNmFkMWYwOGM5OTk5NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dWFj7FYV2bCX4WZUe1PG9HWtD9tEu_zv9E7RECkk6FI)
> 
> Then you can call this service from automation, or from a button card...
> 
> There are some other javascript codes, e.g. to refresh the page the javascript code is `document.location.reload();`

did try this but didn't seem to work which is a shame..the command was sent and a green tick to state as much, but no change at the device itself.   other than having browsermod in place, are there any other things that would stop this from working or would be required to ensure this works?

**Comment by mathoudebine** [comment]
Maybe a javascript blocker can be the cause. You can try to disable any adblocker / use a private browsing window. Under "Targets" > "Choose device" are you able to select your browser?

**Comment by jouster1974** [comment]
i can choose the browser correctly...it sees it...but it just doesnt seem to do anything

![image](https://github.com/user-attachments/assets/64e0e296-8eab-4dab-af1f-04a5df86dca9)
